#!/bin/bash

# ----------- USER CONFIGURATION ---------------

# Кількість повідомлень програми.
VERBOSITY="--verbosity 1"

# Каталог з налаштуваннями.
CONFIGDIR="/usr/local/etc/backup"

# Файл конфігурації в каталогі $CONFIGDIR. Файл в форматі bash, з визначеними
# змінними та двома функціями, preexec та postexec. Ці функції виконуються
# перед початком бекапа та після його завершення. Цей параметр зазвичай
# задається в скриптах для конкретних типів бекапу.
# CONFIG=

# Подальші визначення змінних зазвичай задаються в файлі налаштувань $CONFIG.

# Шлях до корневого каталогу в якому розміщені дані для зберігання.
# SOURCEDIR="/"

# Шлях куди зберігаються резервіні копії.
# TARGETDIR="file://"

# Текстовий файл в каталогі $CONFIGDIR зі списком каталогів і файлів для
# резервного зберігання. Якщо не задано то зберігаються всі файли із #SOURCEDIR.
# INCLUDE_FILELIST=

# Період через який робляться повні бекапи.
# FULLAGE="90D"

# Період який зберігаються бекапи.
# OLDAGE="180D"

# Параметри шифрування.
# ENCRYPTION="--no-encryption"
# ENCRYPTION="--encrypt-key $ENCKEY --sign-key $SIGNKEY"

# ------------------- MAIN ---------------------

# PATH=/bin:/sbin:/usr/bin:/usr/sbin
# umask 117

# Перевірка користувача root
if [ ! `whoami` = root ]; then
	echo "this script must be run as root" 1>&2
	#exit 1
fi

# Перевірка чи заданий файл налаштувань
if [ ! -f "$CONFIGDIR/$CONFIG" ]; then
	echo "config not found" 1>&2
	exit 2
fi

source "$CONFIGDIR/$CONFIG" || exit 2


usage() {
	echo "Usage:"
	echo "$0 [full] [options]"
	echo "$0 restore [options] [--file-to-restore <relpath>]"
	echo "        [--time time] target_directory"
	echo "$0 list-current-files [options] [--time time]"
	echo "$0 collection-status [options] [--file-changed <relpath>]"
	echo
	echo "See also duplicity"
}

backup() {
	preexec
	duplicity cleanup\
		--force\
		$ENCRYPTION\
		$VERBOSITY\
		"$TARGETDIR"
	if [ -n "$OLDAGE" ]; then
		duplicity remove-older-than $OLDAGE\
			--force\
			$ENCRYPTION\
			$VERBOSITY\
			"$TARGETDIR"
	fi
	# Якщо задано файл зі списком каталогів/файлів для бекапу
	if [ -n "$INCLUDE_FILELIST" ]; then
		INCLUDE_FILELIST="--include-filelist\
			$CONFIGDIR/$INCLUDE_FILELIST --exclude"
		EXCTMPL="**"
	fi
	# Якщо задано період через який потрібно робити повну копію
	if [ -n "$FULLAGE" ]; then
		FULLAGE="--full-if-older-than $FULLAGE"
	fi
	backup_type=$1
	shift
	duplicity $backup_type\
		--exclude-device-files\
		--no-print-statistics\
		$ENCRYPTION\
		$VERBOSITY\
		$INCLUDE_FILELIST "$EXCTMPL"\
		$FULLAGE\
		"$@"\
		"$SOURCEDIR"\
		"$TARGETDIR"
	postexec
}

restore() {
	shift
	duplicity restore\
		--no-encryption\
		--verbosity 3\
		"${@:1:$#-1}"\
		"$TARGETDIR"\
		"${@:$#}"
		
}

case "$1" in
	collection-status)
		duplicity "$@" "$TARGETDIR"
		;;
	list-current-files)
		duplicity "$@" "$TARGETDIR"
		;;
	restore)
		restore "$@"
		;;
	full)
		backup "$@"
		;;
	--* | "")
		backup incremental "$@"
		;;
	help | *)
		usage
		;;
esac
exit 0

# -------------------- END ---------------------
